name: Update Repository structure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed 

jobs:
  detect-and-update-structure:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Run update script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/scripts/update_structure.py

      - name: Commit and push if changed
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com" 
          git config user.name "github-actions[bot]"
          git add . 
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update repo structure" && git push)
